# **Day 7 — Assignment**

**Date-Time Data — extended practice**

**Section 1 — Datetime Module Basics**

**Task 1:** Create a date object for March 15th, 2024 using date(). Also create the string
'2024-03-15'. Print both and check their types — confirm they look identical but are NOT
the same type.

In [7]:
# import the modules

import pandas as pd
from datetime import datetime, date, time, timedelta

date1 = date(2024, 3, 15)
print(date1)
print(type(date1))

string1 = "2024-03-15"
print(string1)
print(type(string1))

2024-03-15
<class 'datetime.date'>
2024-03-15
<class 'str'>

**Task 2:** Get today's date with date.today(). Print the day, month, and year separately

In [12]:
date_today = date.today()
print(date_today)
print(date_today.day)
print(date_today.month)
print(date_today.year)

2026-07-02
2
7
2026

**Task 3:** Create a time object for 9:15:45 AM with 250 microseconds. Print the hour,
minute, second, and microsecond separately.

In [14]:
time_1 = time(9, 15, 45, 250)
print(time_1)
print(time_1.hour)
print(time_1.minute)
print(time_1.second)
print(time_1.microsecond)

09:15:45.000250
9
15
45
250

**Task 4:** Combine a date and a time into one datetime object for March 15th, 2024 at
9:15:45 AM, using the datetime() constructor directly.

In [17]:
datetime_1 = datetime(2024, 3, 15, 9, 15, 45)
print(datetime_1)

2024-03-15 09:15:45

**Task 5:** Get the current moment with datetime.now(). Print both .weekday() and
.isoweekday() for it, and note which day of the week that actually is.

In [23]:
datetime_now = datetime.now()
print(datetime_now.weekday())               # index starts (Monday) at [0] -> 3 = Thursday
print(datetime_now.isoweekday())            # index starts (Monday) at [1] -> 4 = Thursday

3
4

**Task 6:** Using that same current moment, find which numbered week of the year it falls
in.

In [24]:
print("Week of the year: ", datetime_now.isocalendar()[1])

Week of the year:  27

**Section 2 — strptime and strftime**

**Task 7:** Parse the string '15 March, 2024 09:30:00' into a real datetime object using
strptime().

In [31]:
string_2 = "15 March, 2024 09:30:00"
date2 = datetime.strptime(string_2,'%d %B, %Y %H:%M:%S')
print(date2)

2024-03-15 09:30:00

**Task 8:** Parse the string '2024-03-15' into a datetime object two ways: once as a full
datetime, and once chained with .date() to get just the date portion. Print both results
and their types.

In [ ]:
string_3 = '2024-03-15'
datetime_full = datetime.strptime(string_3, '%Y-%m-%d')
print(datetime_full, type(datetime_full))
datetime_extract = datetime.strptime(string_3, '%Y-%m-%d').date()           # .date() -> date portion
print(datetime_extract, type(datetime_extract))

2024-03-15 00:00:00 <class 'datetime.datetime'>
2024-03-15 <class 'datetime.date'>

**Task 9:** Take the current datetime and format it into a string that reads like 'Sunday,
June 28, 2026 at 11:04 AM' — full weekday name, full month name, day, year, and 12-
hour time with AM/PM.

In [ ]:
# from Task 5: datetime_now = datetime.now()

print(datetime_now)

datestring_now = datetime_now.strftime('%A, %B %d, %Y at %I:%M %p')
print(datestring_now)

2026-07-02 12:11:29.354532
Thursday, July 02, 2026 at 12:11 PM

**Section 3 — Timedelta Calculations**

**Task 10:** Create two datetime objects: January 1st, 2023 at 8:00 AM, and June 15th,
2024 at 5:30 PM. Subtract the earlier one from the later one and print the resulting
timedelta, along with its .days and .seconds attributes.

In [52]:
dt1 = datetime(2023, 1, 1, 8, 0)
print(dt1)
dt2 = datetime(2024, 6, 15, 17, 30)
print(dt2)

td1 = dt2 - dt1
print(td1)
print(td1.days, "days")
print(td1.seconds, "seconds")

2023-01-01 08:00:00
2024-06-15 17:30:00
531 days, 9:30:00
531 days
34200 seconds

**Task 11:** Take that same duration and convert it into a number of hours, and separately
into a number of minutes

In [65]:
# no attributes for hours and minutes in timedelta -> use the days and seconds
# td1 = 531 days, 34200 seconds

print("Hours: ", td1.days * 24 + td1.seconds / 3600)
print("Minutes: ", td1.days * 24 * 60 + td1.seconds / 60)

Hours:  12753.5
Minutes:  765210.0

**Task 12:** Starting from March 15th, 2024, calculate the date 10 days later and the date
3 weeks earlier.

In [144]:
startdate = datetime(2024, 3, 15)
date_later = startdate + timedelta(days=10)
print(date_later)
date_earlier = startdate - timedelta(weeks=3)
print(date_earlier)

2024-03-25 00:00:00
2024-02-23 00:00:00

**Section 4 — Pandas Datetime, date_range, and the .dt Accessor**

**Task 13:** Use pd.to_datetime() to parse the string '3rd 9 2024'. What type comes back,
and does pandas raise any warning?

In [80]:
datestring = "3rd 9 2024"
date_string =pd.to_datetime(datestring)
print(date_string)                                   # no warning, day and month (presumably) swapped

2024-03-09 00:00:00

**Task 14:** Use pd.date_range() to generate every day in September 2024 (from 2024-
09-01 to 2024-09-30). How many dates are in the result?

In [ ]:
daterange = pd.date_range(start="2024-09-01", end="2024-09-30", freq="D")
print(daterange)
print(len(daterange))               # length of the index -> number of dates

DatetimeIndex(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
               '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08',
               '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12',
               '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16',
               '2024-09-17', '2024-09-18', '2024-09-19', '2024-09-20',
               '2024-09-21', '2024-09-22', '2024-09-23', '2024-09-24',
               '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28',
               '2024-09-29', '2024-09-30'],
              dtype='datetime64[us]', freq='D')
30

**Task 15:** Use pd.date_range() again, this time starting at 2024-09-01 and asking for 14
periods instead of an end date.

In [86]:
daterange2 = pd.date_range(start="2024-09-01", periods=14, freq="D")
print(daterange2)

DatetimeIndex(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
               '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08',
               '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12',
               '2024-09-13', '2024-09-14'],
              dtype='datetime64[us]', freq='D')

**Task 16:** Build a small DataFrame with three columns: Order_date (8 consecutive days
starting 2024-01-01), Ship_date (8 weekly dates starting 2024-01-01), and Priority (8
random integers from 1 to 3). Then add two more columns using the .dt accessor:
Order_month (the month number of Order_date) and Ship_day_of_week (the day name
of Ship_date).

In [151]:
import numpy as np       # import numpy for random numbers

order_dates = pd.date_range(start="2024-01-01", periods=8, freq="D")        # 8 consecutive days
ship_dates = pd.date_range(start="2024-01-01", periods=8, freq="7D")        # 8 weekly dates - freq "W" would return 2024-01-07 in the first row

priority = np.random.randint(1, 4, size=8)                                  # 8 random integers from 1 to 3

# Building the DataFrame
df = pd.DataFrame({"Order_date": order_dates, "Ship_date": ship_dates, "Priority": priority})
df

  Order_date  Ship_date  Priority
0 2024-01-01 2024-01-01         3
1 2024-01-02 2024-01-08         2
2 2024-01-03 2024-01-15         3
3 2024-01-04 2024-01-22         2
4 2024-01-05 2024-01-29         1
5 2024-01-06 2024-02-05         1
6 2024-01-07 2024-02-12         3
7 2024-01-08 2024-02-19         2

In [ ]:
df["Order_month"] = df["Order_date"].dt.month               # adding order month
df["Ship_day_of_week"] = df["Ship_date"].dt.day_name()      # adding ship day
df

  Order_date  Ship_date  Priority  Order_month Ship_day_of_week
0 2024-01-01 2024-01-01         1            1           Monday
1 2024-01-02 2024-01-08         2            1           Monday
2 2024-01-03 2024-01-15         1            1           Monday
3 2024-01-04 2024-01-22         2            1           Monday
4 2024-01-05 2024-01-29         2            1           Monday
5 2024-01-06 2024-02-05         1            1           Monday
6 2024-01-07 2024-02-12         2            1           Monday
7 2024-01-08 2024-02-19         2            1           Monday

**Section 5 — Standalone Practice Questions**

**Task 17:** Write a function that checks whether a year is a leap year, and test it on 1996,
2100, 2400, and 2023.

In [155]:
year = 2023

is_leap_year = (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)
print(is_leap_year)

False

**Task 18:** Convert the string 'Dec 25 2023 6:15 AM' into a real datetime object.

In [102]:
string2 = 'Dec 25 2023 6:15 AM'
date_string2 = datetime.strptime(string2, "%b %d %Y %I:%M %p")
print(date_string2)

2023-12-25 06:15:00

**Task 19:** Starting from February 28th, 2020, find the date exactly 10 days later.

In [105]:
start = date(2020, 2, 28)
date_10later = start + timedelta(days=10)
print(date_10later)

2020-03-09

**Task 20:** Convert the Unix timestamp 1700000000 into a readable local datetime. Then
separately, print yesterday's date, today's date, and tomorrow's date.

In [111]:
timestamp = 1700000000
readable_date = datetime.fromtimestamp(timestamp)
print(readable_date)

today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print(today)
print(yesterday)
print(tomorrow)

2023-11-14 23:13:20
2026-07-02
2026-07-01
2026-07-03

**Section 6 — Real Dataset Application**

**Task 21:** Read bike_share_data.csv. Check the dtype of the Start Date and End Date
columns — are they real datetime columns, or plain text?

In [120]:
# load bike_share_data

bike_share = pd.read_csv('../data/bike_share_data.csv')
bike_share.head()

,Trip ID,Duration,Start Date,Start Station,Start Terminal,End Date,End Station,End Terminal,Bike #,Subscription Type,Zip Code
0,4576,63,8/29/2013 14:13,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127
1,4607,70,8/29/2013 14:42,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138
2,4130,71,8/29/2013 10:16,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214
3,4251,77,8/29/2013 11:29,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060
4,4299,83,8/29/2013 12:02,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103

Both columns look like datetime...

In [121]:
bike_share.info()

<class 'pandas.DataFrame'>
RangeIndex: 144015 entries, 0 to 144014
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Trip ID            144015 non-null  int64
 1   Duration           144015 non-null  int64
 2   Start Date         144015 non-null  str
 3   Start Station      144015 non-null  str
 4   Start Terminal     144015 non-null  int64
 5   End Date           144015 non-null  str
 6   End Station        144015 non-null  str
 7   End Terminal       144015 non-null  int64
 8   Bike #             144015 non-null  int64
 9   Subscription Type  144015 non-null  str
 10  Zip Code           137885 non-null  str
dtypes: int64(5), str(6)
memory usage: 12.1 MB

... but they are strings.

**Task 22:** Convert both Start Date and End Date to real datetime columns using
pd.to_datetime(), and confirm the dtype change with info().

In [126]:
# converting original columns into datetime
bike_share['Start Date'] = pd.to_datetime(bike_share['Start Date'])      # converting original columns into datetime
bike_share['End Date'] = pd.to_datetime(bike_share['End Date'])

bike_share.info()

<class 'pandas.DataFrame'>
RangeIndex: 144015 entries, 0 to 144014
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Trip ID            144015 non-null  int64
 1   Duration           144015 non-null  int64
 2   Start Date         144015 non-null  datetime64[us]
 3   Start Station      144015 non-null  str
 4   Start Terminal     144015 non-null  int64
 5   End Date           144015 non-null  datetime64[us]
 6   End Station        144015 non-null  str
 7   End Terminal       144015 non-null  int64
 8   Bike #             144015 non-null  int64
 9   Subscription Type  144015 non-null  str
 10  Zip Code           137885 non-null  str
dtypes: datetime64[us](2), int64(5), str(4)
memory usage: 12.1 MB

**Task 23:** Using the .dt accessor on your newly-converted Start Date column, create two
new columns: start_hour (the hour of day the trip started) and start_day_of_week (the
full day name). Then use value_counts() on start_day_of_week to see which day has
the most trips.

In [157]:
bike_share['start_hour'] = bike_share['Start Date'].dt.hour                     # creating hour column
bike_share['start_day_of_week'] = bike_share['Start Date'].dt.day_name()        # creating start day column
bike_share.head()

,Trip ID,Duration,Start Date,Start Station,Start Terminal,End Date,End Station,End Terminal,Bike #,Subscription Type,Zip Code,start_hour,start_day_of_week
0,4576,63,2013-08-29 14:13:00,South Van Ness at Market,66,2013-08-29 14:14:00,South Van Ness at Market,66,520,Subscriber,94127,14,Thursday
1,4607,70,2013-08-29 14:42:00,San Jose City Hall,10,2013-08-29 14:43:00,San Jose City Hall,10,661,Subscriber,95138,14,Thursday
2,4130,71,2013-08-29 10:16:00,Mountain View City Hall,27,2013-08-29 10:17:00,Mountain View City Hall,27,48,Subscriber,97214,10,Thursday
3,4251,77,2013-08-29 11:29:00,San Jose City Hall,10,2013-08-29 11:30:00,San Jose City Hall,10,26,Subscriber,95060,11,Thursday
4,4299,83,2013-08-29 12:02:00,South Van Ness at Market,66,2013-08-29 12:04:00,Market at 10th,67,319,Subscriber,94103,12,Thursday

In [158]:
print(bike_share['start_day_of_week'].value_counts())       # getting the trips by start day

start_day_of_week
Thursday     25265
Tuesday      24678
Friday       24283
Wednesday    23651
Monday       23138
Saturday     12413
Sunday       10587
Name: count, dtype: int64