# **Day 5 — Assignment**

**Numpy Fundamentals — arrays, broadcasting, aggregation, and a pivot table**

**Section 1 — Array Creation & Casting**

**Task 1:** Create an array from the list [2, 4, 6, 8, 10]. Then create a second array from
the same values as a tuple instead, explicitly forcing dtype to np.int32. Check both
dtypes.

In [2]:
import numpy as np                  # importing the module

In [13]:
first_array = np.array([2, 4, 6, 8, 10])                            # square brackets
first_tuple = np.array((2, 4, 6, 8, 10), np.int32)                  # standard brackets

In [12]:
print(first_array.dtype)
print(first_tuple.dtype)

int64
int32

int64 as default data type

**Task 2:** Create an array mixing strings and numbers: ["3", 7, 9, "12", 5]. Check its dtype
and explain what happened. Then force dtype=np.int32 on the same values — it should
work. Finally, swap "12" for "girl" and force dtype=np.int32 again — what happens this
time?

In [27]:
second_array = np.array(["3", 7, 9, "12", 5])
print(second_array.dtype)
second_array

<U21

array(['3', '7', '9', '12', '5'], dtype='<U21')

Second array was transformed in a (2-character unicode) string

In [17]:
second_array = np.array(["3", 7, 9, "12", 5], np.int32)
print(second_array.dtype)

int32

-> Works, numeric looking strings can be easily transformed into numbers

In [32]:
second_array = np.array(["3", 7, 9, "Girl", 5], np.int32)
print(second_array.dtype)

ValueError: invalid literal for int() with base 10: 'Girl'

Error occurs, because "Girl" can't be transformed into a (int32) number

**Task 3:** Create: a 3x5 array of zeros, a 2x6 array of ones, a 5x5 identity matrix, and an
array running from 0 to 20 in steps of 2.5.

In [20]:
third_array = np.zeros((3, 5))
third_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
fourth_array = np.ones((2, 6))
fourth_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
id_array = np.identity(5)
id_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
fifth_array = np.arange(0, 21, 2.5)                             # end argument = 21, so 20 will be included
fifth_array

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

**Section 2 — Math & Broadcasting**

**Task 4:** Create two 1D arrays of 4 numbers each. Add them together, then multiply
them together, element-wise

In [30]:
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])

print(array_1 + array_2)                        # addition
print(array_1 * array_2)                        # multiplication

[ 6  8 10 12]
[ 5 12 21 32]

**Task 5:** Create a 2x2 array and multiply every element by 10 using broadcasting.

In [ ]:
array_3 = np.array([[1, 4], [5, 8]])
array_3 * 10                                            # multiplication

array([[10, 40],
       [50, 80]])

**Task 6:** Create a different 2x2 array. Subtract [1, 2] from it (column-wise broadcasting),
then subtract [[1], [2]] from it (row-wise broadcasting). Explain the difference in the
results.

In [40]:
array_4 = np.array([[2, 8], [1, 7]])
array_4

array([[2, 8],
       [1, 7]])

In [39]:
print(array_4 - [1, 2])                             # column-wise: subtract 1 from the first and 2 from the second columns

[[1 6]
 [0 5]]

In [ ]:
print(array_4 - [[1], [2]])                         # row-wise: subtract 1 from the first and 2 from the second row

[[ 1  7]
 [-1  5]]

**Section 3 — Indexing & Aggregation**

**Task 7:** Build a 4x5 array using arange() and reshape(), containing the numbers 0
through 19. Grab row 1 on its own, then column 3 on its own, then the sub-block
spanning rows 1–2 and columns 2–3.

In [56]:
range_array = np.arange(0, 20, 1).reshape(4, 5)         # end-argument = 20
range_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
row1 = range_array[1]                   # no second index -> grabbing the row
print(row1)

[5 6 7 8 9]

In [ ]:
column3 = range_array[:, 3]             # column 3 of each row
print(column3)

[ 3  8 13 18]

In [64]:
subset = range_array[0:2, 1:3]          # column 2 and 3 of rows 1 and 2, indices are end exclusive
print(subset)

[[1 2]
 [6 7]]

**Task 8:** On that same array, compute: the sum along axis=0, the mean along axis=1,
the max along axis=0, and the min along axis=1.

In [65]:
range_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
range_array.sum(axis=0)                             # returning column totals

array([30, 34, 38, 42, 46])

In [ ]:
range_array.mean(axis=1)                            # returning the means for each row

array([ 2.,  7., 12., 17.])

In [ ]:
range_array.max(axis=0)                             # max values for each column

array([15, 16, 17, 18, 19])

In [ ]:
range_array.min(axis=1)                             # min values for each line

array([ 0,  5, 10, 15])

**Task 9:** Find the index of the minimum value in each column (axis=0), and the index of
the single largest value in the entire array

In [71]:
range_array.argmin(axis=0)                     # minimum values in each column occur at row 1 (index 0)

array([0, 0, 0, 0, 0])

In [73]:
range_array.argmax()                           # returning the index of the flattened array (before reshaping)

np.int64(19)

**Task 10:** Compute the cumulative sum along axis=1, and then flatten the array back
into one dimension.

In [ ]:
print(range_array)
range_array.cumsum(axis=1)                  # cumulative sum of the rows (summing up along the columns)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60],
       [15, 31, 48, 66, 85]])

In [75]:
range_array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**Section 4 — np.where() and a Pivot Table**

**Task 11:** Using the same 4x5 array from Section 3, find the positions of every value
greater than 15, and separately, the position of the value 7.

In [76]:
np.where(range_array > 15)

(array([3, 3, 3, 3]), array([1, 2, 3, 4]))

-> Values bigger than 15 occur in row 4 columns 2-5

In [77]:
np.where(range_array == 7)

(array([1]), array([2]))

-> We find value 7 in row 2, column 3

**Task 12:** Read winequality-white.csv. Use pd.cut() to split the alcohol column into 5
equal-width bins, name the new column alcohol_bin, and attach it to the DataFrame.
Then build a pivot table showing average residual sugar, with quality as the rows and
alcohol_bin as the columns.

In [ ]:
import pandas as pd                 # importing pandas for reading csv

In [103]:

white_wine_df = pd.read_csv('../data/winequality-white.csv', delimiter=';')     # loading white wine data
white_wine_df.shape
white_wine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')

In [ ]:
white_wine_df["alcohol_bin"] = pd.cut(white_wine_df["alcohol"], bins=5)                     # splitting alcohol column into 5 bins

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alcohol_bin
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,"(7.994, 9.24]"
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,"(9.24, 10.48]"
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,"(9.24, 10.48]"
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,"(9.24, 10.48]"
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,"(9.24, 10.48]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,"(10.48, 11.72]"
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,"(9.24, 10.48]"
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,"(9.24, 10.48]"
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,"(11.72, 12.96]"
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,"(11.72, 12.96]"

In [105]:
pd.pivot_table(white_wine_df, values="residual sugar", index="quality", columns="alcohol_bin", aggfunc="mean")

alcohol_bin,"(7.994, 9.24]","(9.24, 10.48]","(10.48, 11.72]","(11.72, 12.96]","(12.96, 14.2]"
quality,,,,,
3,5.475000,6.825000,7.406250,2.875000,NaN
4,8.098529,4.079054,3.187778,3.627778,1.100000
5,10.634988,6.826370,4.224259,4.145000,1.300000
6,11.891196,7.203793,4.749361,3.799304,4.039535
7,13.786667,6.239744,4.025633,4.084333,4.203472
8,13.311111,5.718182,5.185106,4.793210,3.225000
9,NaN,10.600000,NaN,2.500000,NaN